### PR TITLE
Workflow: Enable docker cache, allow manual publish, correct docker repo log in and GitHub token usage (again)

### PR DESCRIPTION
**Pull request by Laxystem**
Well-merged version of #1.

### CODE REVIEW

**Comment by saiwal** [comment]
thanks! :)

**Comment by saiwal** [comment]
@Laxystem i am getting a build error. 
`Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/saiwal/hubzilla-docker:latest: unexpected status from POST request to https://ghcr.io/v2/saiwal/hubzilla-docker/blobs/uploads/: 403 Forbidden`

**Comment by Laxystem** [comment]
> @Laxystem i am getting a build error. `Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/saiwal/hubzilla-docker:latest: unexpected status from POST request to https://ghcr.io/v2/saiwal/hubzilla-docker/blobs/uploads/: 403 Forbidden`

Weird. It [works](https://github.com/Laxystem/JoinFedivriHubzillaDocker/actions/runs/11997591352) for me. ~~Is that a manual run?~~ Oh, I see it is.

Try clearing the cache, perhaps.

**Comment by saiwal** [comment]
the issue was with using GITHUB_TOKEN instead of GH_PAT. I've reinstated GH_PAT for now. will try to pin-point the reason for this. But from what i read, GH_PAT seems to be better since its scope is limited to the current repo.

**Comment by Laxystem** [comment]
> the issue was with using GITHUB_TOKEN instead of GH_PAT. I've reinstated GH_PAT for now. will try to pin-point the reason for this. But from what i read, GH_PAT seems to be better since its scope is limited to the current repo.

How so? This must mean you need to add more `permissions`.

**Pull request merged**
