### PR TITLE
Workflow: Enable docker cache, allow manual publish, correct docker repo log in and GitHub token usage

### PR DESCRIPTION
**Pull request by Laxystem**

### CODE REVIEW

**Comment by Laxystem** [comment]
Wait @saiwal, this won't work... I've accidentally done the merge wrong

I'll send another PR fixing this in a moment, in the meanwhile, revert this please.

**Comment by saiwal** [comment]
ok

**Comment by Laxystem** [comment]
> ok

can you revert this? I can't create the new PR before you do...

**Comment by saiwal** [comment]
have reset the merge

**Pull request merged**
